// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKAo5AxbJvhxpyGi4sKqmTCXo5ObYeJec',
    appId: '1:705705266782:web:2427f0af7f4abcf7756ecf',
    messagingSenderId: '705705266782',
    projectId: 'vb-diary-app-67125',
    authDomain: 'vb-diary-app-67125.firebaseapp.com',
    databaseURL: 'https://vb-diary-app-67125-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vb-diary-app-67125.firebasestorage.app',
    measurementId: 'G-K5JMDJEC3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmiybwgE-roMCY461BmNKml6tV5PyV_ac',
    appId: '1:705705266782:android:933f1a33c31c7cf9756ecf',
    messagingSenderId: '705705266782',
    projectId: 'vb-diary-app-67125',
    databaseURL: 'https://vb-diary-app-67125-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vb-diary-app-67125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBQdUPpUnL5mk6s02yH1FERrsuPG7r4D4',
    appId: '1:705705266782:ios:e77a175f83796f38756ecf',
    messagingSenderId: '705705266782',
    projectId: 'vb-diary-app-67125',
    databaseURL: 'https://vb-diary-app-67125-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vb-diary-app-67125.firebasestorage.app',
    androidClientId: '705705266782-aituag8qd3sa8cpskcijt2g0ggf253b8.apps.googleusercontent.com',
    iosClientId: '705705266782-mflgv7boptuc0ae65102c93sg44pt63g.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBQdUPpUnL5mk6s02yH1FERrsuPG7r4D4',
    appId: '1:705705266782:ios:e77a175f83796f38756ecf',
    messagingSenderId: '705705266782',
    projectId: 'vb-diary-app-67125',
    databaseURL: 'https://vb-diary-app-67125-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vb-diary-app-67125.firebasestorage.app',
    androidClientId: '705705266782-aituag8qd3sa8cpskcijt2g0ggf253b8.apps.googleusercontent.com',
    iosClientId: '705705266782-mflgv7boptuc0ae65102c93sg44pt63g.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKAo5AxbJvhxpyGi4sKqmTCXo5ObYeJec',
    appId: '1:705705266782:web:37f186f31c03e927756ecf',
    messagingSenderId: '705705266782',
    projectId: 'vb-diary-app-67125',
    authDomain: 'vb-diary-app-67125.firebaseapp.com',
    databaseURL: 'https://vb-diary-app-67125-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vb-diary-app-67125.firebasestorage.app',
    measurementId: 'G-G0Y4DY36HX',
  );

}